// <auto-generated />
using BSUIRQueueTelegramBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSUIRQueueTelegramBot.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("BSUIRQueueTelegramBot.Data.Record", b =>
                {
                    b.Property<int>("Place")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Place", "Subject");

                    b.ToTable("records");
                });
#pragma warning restore 612, 618
        }
    }
}
